# Generated by Django 2.0 on 2019-11-29 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='image',
            field=models.ImageField(default='abc.jpg', upload_to='img/'),
        ),
    ]
