# Generated by Django 2.0 on 2019-12-02 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20191130_1001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='image',
        ),
        migrations.AddField(
            model_name='doctor',
            name='pic',
            field=models.ImageField(default='abc.jpg', upload_to='img/'),
        ),
    ]
