# Generated by Django 2.0 on 2019-12-02 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20191202_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='pic',
            field=models.ImageField(default='abc.jpg', upload_to='img/'),
        ),
    ]
