# Generated by Django 2.0 on 2019-12-02 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_patient_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='pic',
            new_name='pic2',
        ),
    ]
