# Generated by Django 2.0 on 2019-12-02 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20191202_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='pic2',
            field=models.ImageField(default='can.jpg', upload_to='img/'),
        ),
    ]
